### ISSUE TITLE
not respond

### ISSUE THREAD

**Issue by juanpradana** [merkremont/LineChivas#1]
that bot are succes login. but, why not respond? can't join grup, can't send msg, can't all? can you help me?

**Comment by merkremont** [comment]
Open _chivasbot.py_ then search `YOUR_MID_HERE` and edit with your MID code ( can you get from `cl.getProfile().mid` )
Example :
`admin=["ua8bas877a69a0fa7s7f9a79a"]`

**Comment by merkremont** [comment]
Can you send what error showing?

**Comment by yekayee** [comment]
Traceback (most recent call last):
  File "LineApi.py", line 2, in <module>
    from Api import Poll, Talk, channel
  File "C:\Users\kaye\Desktop\LineChivas-master\LineAlpha\Api\__init__.py", line
 1, in <module>
    from Talk import Talk
  File "C:\Users\kaye\Desktop\LineChivas-master\LineAlpha\Api\Talk.py", line 3,
in <module>
    import requests, rsa
ImportError: No module named requests

why?

**Comment by merkremont** [comment]
@yekayee 
Install python packages: _requests, rsa_

`$ pip install requests`
`$ pip install rsa`

**Comment by juanpradana** [comment]
@merkremont no error showing, just notifed login succes. But why that bots not respons?

_Sent from my Xiaomi Redmi Pro using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by juanpradana** [comment]
@merkremont can you send your id line by email? My email: suarahp@gmail.com

_Sent from my Xiaomi Redmi Pro using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by merkremont** [comment]
Send me a dm on my [twitter](https://twitter.com/merkremont)
