### ISSUE TITLE
Why Everyone can command

### ISSUE THREAD

**Issue by winlianclub** [merkremont/LineChivas#10]
Sorry i want ask again, why everyone can command Bot at room ???

May i must to change that's MID ???
admin=["YOUR_MID_HERE"]

What's the mean of "global name 'k3' is not defined" ???

Help me please

**Comment by Gabrieeeltd** [comment]
Yea replace "YOUR_MID_HERE_" with your MID, u have to type "MID" and send it to one of the group you have. Don't do it on your friend's private chat, it would only take their MID instead of yours.

**Comment by winlianclub** [comment]
Please closed this issue cause u never shared full your skill... thanks
