### ISSUE TITLE
Server returns 403 Forbidden resulting EOFError

### ISSUE THREAD

**Issue by zimethsuki** [merkremont/LineChivas#15]
Hi,

It  seems ChivasBot HTTP Response for getAuthQrcode is 403 Forbidden resuting EOFError for recv_getAuthQrcode.

Any idea / hint to fix this?

Thanks.

**Comment by winlianclub** [comment]
THIS IS TRASH LIB cause @merkremont never shared full his skill and just think money.. :v :v :v 

@zimethsuki PM wae lah ga usah sok inggris tp produk indo pea... ID line : winlian

**Comment by merkremont** [comment]
Please check your internet connection
