### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by opankuswanto** [merkremont/LineChivas#27]
teach me to make bot chivas using termux

**Comment by winlianclub** [comment]
PM me ID : winlian

**Comment by moepoi** [comment]
@winlianclub Lu emgnya bisa apa, cuma bisa bacot doang 😋

**Comment by winlianclub** [comment]
@moepoi saya ga bisa apa apa tp secara KASTA ILMU saya masih lebih pintar daripada kamu :v :v :v

**Comment by f48al** [comment]
@Winlian maling script orang aja kau kontol bangga kau punya ilmu apaan kau brengsek
