### ISSUE TITLE
THIS SCRIPT IS *****

### ISSUE THREAD

**Issue by winlianclub** [merkremont/LineChivas#29]
Thanks for share this script but you must to know @merkremont and @fadhiilrachman ILMU ITU MURAH karena sesama Indo bukan takut saingan tapi saling berbagi... REZEKI SUDAH DI ATUR SOB dan cek sendiri aja kesalahan pada script kamu @merkremont .., saran saya HAPUS AKUN DAH dan jangan sok inggris krn ilmu ini dari Korea... :v :v :v 

Note: saya paling suka hancurin orang PELIT ILMU... remember that !!!

**Comment by arisawali2014** [comment]
Beginilah contoh orang yang cuman bisa pakai tapi tidak bisa memperbaiki! :v Bodoh wakowkaowkaok

**Comment by fadhiilrachman** [comment]
Wkwkwk gaya lu udah kayak orang paling berguna di dunia ini
Eh tong, lu bisa apa selain cuma bisa pake terus ngedit?

Karena github situs internasional, makanya bahasa inggris dipake karena bahasa global. Belajar dulu sono tong baru bisa buka issue yang berguna..

Satu lagi, merk kremont itu orang Jepang asli. Video yang diupload ke youtube itu gua yang buat, makanya gua sama merk kolab buat channel pake nama merk

**Comment by moepoi** [comment]
Hadeuh Biasa lah dia cuma bisa pake doang, disuruh buat gak bisa wkwkw

**Comment by winlianclub** [comment]
Apapun balasan kalian terutama @fadhiilrachman yg tidak tercantum di sini tetap saja lihat point utama saya bahwa saya ucapkan terimakasih sudah share tapi sayang sekali tidak ada namanya PROTEKSI...  Thanks
