### ISSUE TITLE
can't login...

### ISSUE THREAD

**Issue by YogaSakti** [merkremont/LineChivas#3]
what account? 
Personal account or Line@ ???
![image](https://user-images.githubusercontent.com/24309806/29491149-dfb4ffb2-857c-11e7-8e8c-5cc854158105.png)

**Comment by juanpradana** [comment]
@YogaSakti personal account

_Sent from my Xiaomi Redmi Pro using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by YogaSakti** [comment]
4 login?

**Comment by juanpradana** [comment]
@YogaSakti yes, you must loggin from 4 account by qr

_Sent from my Xiaomi Redmi Pro using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by YogaSakti** [comment]
4 different acc??

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by YogaSakti** [comment]
@juanpradana 4 different account?

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by merkremont** [comment]
Yes, because the script need 4 account to login.
If you want only 1 account for needed, just remove part of 

```
kk = LineAlpha.LINE()
kk.login(qr=True)
kk.loginResult()

ki = LineAlpha.LINE()
ki.login(qr=True)
ki.loginResult()

kc = LineAlpha.LINE()
kc.login(qr=True)
kc.loginResult()
```

and add new line for this code 

`kc = ki = kk = cl`

**Comment by yekayee** [comment]
login success
local variable 'profile' referenced before assignment
local variable 'profile' referenced before assignment

why ? @merkremont

**Comment by YogaSakti** [comment]
@merkremont thanks :)
